Output space exploration
quaquel/EMAworkbench pull request #170
Opened 2022-09-14 11:10 UTC by quaquel

adds output space exploration to the workbench. 

- [x] unit tests and documentation are in place.
- [ ] I might still want to update the example notebook
- [ ] unit tests adds pytest-mock as a dependency in ci, and thus also for #166

2022-09-14 12:38 UTC, EwoutH commented
Looks awesome! I will review it from a code-quality and user perspective tomorrow.

2022-09-19 11:10 UTC, EwoutH commented
I started on a review, in general, it looks quite good!

Reviewing the docs on the other hand is quite a challenge without them begin built. Could you check if it's easy to enable doc building (see #171) before I review them?

2022-09-19 12:52 UTC, quaquel commented
I have enabled the building of docs for pull requests. I guess we need one more commit here to trigger it.

2022-09-19 13:25 UTC, EwoutH commented
If you can find the time, [cleaning up you commits](https://dev.to/aman_singh/how-to-cleanup-commit-history-using-git-reset-46p3) would be a great way to also trigger the CI! :)

Otherwise I will do some ci-trigger-magic when I review it (probably tomorrow).

2022-09-20 08:16 UTC, EwoutH commented
Updated the CI and pyproject.toml with pytest-mock.

Read the Docs now runs, and generates the docs for this PR. However, for some reasone the outputspace_exploration module doesn't appear in it: https://emaworkbench--170.org.readthedocs.build/en/170/api_index.html#exploratory-modeling-framework

2022-09-20 09:40 UTC, quaquel commented
Ok, I'll have a look later today. Probably missing links in some index files.

2022-09-20 12:11 UTC, EwoutH commented
Perfect, take your time. I started on the review of the Jupyter example notebook, I hope to finish it later today.

2022-09-20 16:45 UTC, quaquel commented
the docs now are displaying properly. I guess this is ready for a last cleanup of the commit history before being merged, unless you find something in the notebook

2022-09-21 08:34 UTC, EwoutH commented
I just reviewed the notebook, and it's structured quite well! The main thing I'm missing is a bit of explanation and interpretation, from which the viewer can gain a better understanding of this method. It would add a lot of value if this example would be readable on itself, as a primer to OSE.

Reviewing Jupyter notebooks in GitHub turned out to be quite cumbersome, so I searched a bit and found an app, ReviewNB, which made this easy. I left some copies on the notebok, you can view and reply here (you probably have to login with GitHub): https://app.reviewnb.com/EwoutH/EMAworkbench/blob/outputspace_review/ema_workbench%2Fexamples%2Foutputspace_exploration_lakeproblem.ipynb

2022-09-21 09:39 UTC, quaquel commented
That review app looks nice and the suggestions will indeed make the notebook a lot better. I'll try to make the suggested changes over the coming days.

2022-09-22 07:33 UTC, quaquel commented
I have updated the notebook broadly in line with your suggestions. Note that I don't intend for these notebooks to be a tutorial on MOEAs so I have kept the additional text short but with links to relevant literature in case you want to know more.

I also added a small check to ensure the number of items in `grid_spec` matches the number of objectives (analogous to the problem with epsilon values in e-NSGA2). This in turn necessitated a small update to the test code.

2022-09-22 11:52 UTC, quaquel commented
I cleaned the commit history again, so if you agree with the notebook update, this is ready to be merged.

2022-09-23 11:02 UTC, EwoutH requested changes
Code quality and structure looks good, I didn't encounter strange things.

Docs are also coming along nicely, I added a few comments on things I found unclear or ambiguous.

If you take a look at those, could you let me merge afterwards? I will squash it into a nice tidy commit.

2022-09-23 11:38 UTC, quaquel commented on ema_workbench/em_framework/optimization.py
> -    for solution in platypus.unique(platypus.nondominated(optimizer.result)):
First, it is redundant. Optimizer.results already returns the non dominated solutions. Second, it breaks with output space exploration, where we do not want to include directional information.

2022-09-23 11:41 UTC, quaquel commented on ema_workbench/em_framework/evaluators.py
> +    variator : platypus GAOperator instance, optional
Not sure whether I want to go there. By defaulting to None, we trigger the default values within platypus-opt. The default in platypus-opt is Simulated Binary Crossover with Polynomial Mutation. Any custom platypus-opt GAOperator instance is possible, but what that means is covered by platypus-opt.

2022-09-23 11:42 UTC, quaquel commented on ema_workbench/em_framework/outputspace_exploration.py
> +    """A combination of autoadaptive operator selection with OutputSpaceExploration.
problem and grid spec are necessary. The rest has meaningful defaults

2022-09-23 11:46 UTC, quaquel commented on ema_workbench/em_framework/outputspace_exploration.py
> +
If I know how, then yes. This probably overlaps with adding an overview page with links to all examples

2022-09-23 11:47 UTC, quaquel commented on ema_workbench/em_framework/outputspace_exploration.py
> +__all__ = ["OutputSpaceExploration", "AutoAdaptiveOutputSpaceExploration"]
yes and yes.

2022-09-23 11:49 UTC, quaquel commented on ema_workbench/em_framework/outputspace_exploration.py
> +    grid_spec : list of tuples
Technically, you could get away with just the epsilon values. For cross seed comparisons, you would need the a value for the origin of the grid structure, and the epsilon for the size of the grid. I had left it at three for now, but we can change this to a minimum (or origin) and epsilon value.

2022-09-23 11:58 UTC, quaquel commented on ema_workbench/em_framework/outputspace_exploration.py
> +    population_size : int, optional
100

2022-09-23 12:07 UTC, quaquel commented on ema_workbench/em_framework/optimization.py
> -class CombinedMutator(CombinedVariator):
yes that can go.

2022-09-23 12:16 UTC, quaquel commented on ema_workbench/em_framework/outputspace_exploration.py
> +    grid_spec : list of tuples
By the way, which examples do you mean with tuples of 2 values?

2022-09-23 12:23 UTC, quaquel commented on ema_workbench/em_framework/outputspace_exploration.py
> +combined with auto-adaptive population sizing as used in e-NSGAII. This replaces the use of adaptive Cauchy mutation
yes, and link is being added

2022-09-23 13:23 UTC, EwoutH commented on ema_workbench/em_framework/evaluators.py
> +    variator : platypus GAOperator instance, optional
In that case I think I don't understand the _optional_. What happens if you leave `variator` unspecified?

2022-09-23 13:25 UTC, EwoutH commented on ema_workbench/em_framework/outputspace_exploration.py
> +    grid_spec : list of tuples
A few places:

- https://github.com/quaquel/EMAworkbench/pull/170/files#diff-17ddc728ebc309d5ce247a5cb98dcfbb88047b15dfb9bcab0877770da2c3656cR120
- https://github.com/quaquel/EMAworkbench/pull/170/files#diff-14e09aadf560c254302311b901de243dbe999d7fca44a1b4321b0dc0505e05b3R133-R134
- https://github.com/quaquel/EMAworkbench/pull/170/files#diff-427cb03187f4e1f151fcb26edaf2d2752df9faef498122e6b11d10d18c3d78c7R151

2022-09-23 13:32 UTC, quaquel commented on ema_workbench/em_framework/evaluators.py
> +    variator : platypus GAOperator instance, optional
Then it takes its default value, which is None, as with any other keyword argument.

2022-09-23 13:48 UTC, EwoutH commented on ema_workbench/em_framework/outputspace_exploration.py
> +    grid_spec : list of tuples
I read `0, 1, 0.1` as `0.1, 0.1`, whoops...

Maybe format as
```Python
grid_spec = [
    (0, 1, 0.1),
    (0, 1, 0.1),
]
```

2022-09-23 13:49 UTC, EwoutH commented on ema_workbench/em_framework/evaluators.py
> +    variator : platypus GAOperator instance, optional
So should we mention that it uses the platypus-opt default, which is Simulated Binary Crossover with Polynomial Mutation?

2022-09-23 13:55 UTC, quaquel commented on ema_workbench/em_framework/outputspace_exploration.py
> +    grid_spec : list of tuples
yes (see my black comment in #178 )

2022-09-23 14:08 UTC, quaquel commented on ema_workbench/em_framework/evaluators.py
> +    variator : platypus GAOperator instance, optional
I added a bit to the documentation

2022-09-23 14:09 UTC, quaquel commented
I think this is now ready to be merged

2022-09-23 14:24 UTC, EwoutH commented
Awesome, I agree!

Can I merge #178? Then I will throw in some CI, rebase and check if #170 passes, and then merge it.

2022-09-23 14:24 UTC, EwoutH approved these changes

2022-09-23 16:16 UTC, quaquel commented
go ahead

2022-09-23 21:30 UTC, merged

2022-09-23 21:32 UTC, EwoutH commented
@quaquel It's in, congratulations on an amazing new feature!